name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Set up dependencies
        run: go get .
        
      - name: Build
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v ./...